name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URI: postgres://postgres:pgs3cr3t@postgres:5432/testdb
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install --force-reinstall psycopg2-binary
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h postgres -p 5432 && echo "PostgreSQL is ready!" && break || sleep 5;
          done

      - name: Check psycopg2-binary version
        run: |
          python -c "import psycopg2; print(psycopg2.__version__)"

      - name: Verify SQLAlchemy connection
        run: |
          python -c "
          from sqlalchemy import create_engine;
          engine = create_engine('postgresql://postgres:pgs3cr3t@postgres:5432/testdb');
          conn = engine.connect();
          print('Connection successful');
          conn.close();
          "

      - name: Debug environment
        run: |
          echo "Python version:"
          python --version
          echo "Installed packages:"
          pip list
          echo "Environment variables:"
          env

      - name: Run unit tests with Nose
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=service
